
package bmcambumbito;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JOptionPane;

/**
 *
 * @author Oliver Smit, Camil Agramonte y Luis Feliz <BmCambumbito at gmail.com>
 */
public class registro extends javax.swing.JFrame {

    /**
     * Creates new form registro
     */
    public registro() {
        initComponents();
        setLayout(null);
        this.setLocationRelativeTo(null);
        setTitle("Register");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("img/ice.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator11 = new javax.swing.JSeparator();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        contrasena = new javax.swing.JPasswordField();
        confirmar = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        pais = new javax.swing.JComboBox<>();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        code = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        user1 = new javax.swing.JTextField();
        mail1 = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        ciudad = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        sexo = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmcambumbito/img/ice.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 230, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmcambumbito/img/bglogin.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 820));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 132, 818, 10));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Corbel", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("Registrar Receptor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 70, 300, -1));

        jRadioButton2.setText("jRadioButton2");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1453, 317, -1, -1));

        jLabel4.setFont(new java.awt.Font("Corbel", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nombre");
        jLabel4.setEnabled(false);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Corbel", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Email");
        jLabel5.setEnabled(false);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Corbel", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Telefono");
        jLabel6.setEnabled(false);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, -1, -1));

        jLabel7.setFont(new java.awt.Font("Corbel", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Apellido");
        jLabel7.setEnabled(false);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Corbel", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Code");
        jLabel9.setEnabled(false);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 420, -1, -1));

        contrasena.setBackground(new java.awt.Color(255, 255, 255));
        contrasena.setForeground(new java.awt.Color(0, 0, 0));
        contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaActionPerformed(evt);
            }
        });
        jPanel1.add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 281, 30));

        confirmar.setBackground(new java.awt.Color(255, 255, 255));
        confirmar.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, 288, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 218, 281, 14));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 281, 14));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 281, 14));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 281, 14));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 280, 14));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 480, 120, 14));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 281, 14));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 550, 283, 14));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 281, 14));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 110, 10));

        pais.setBackground(new java.awt.Color(255, 255, 255));
        pais.setForeground(new java.awt.Color(0, 0, 0));
        pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rep. Dom.", "" }));
        pais.setToolTipText("");
        pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisActionPerformed(evt);
            }
        });
        jPanel1.add(pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 280, 30));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 298, 10));

        jLabel10.setFont(new java.awt.Font("Corbel", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Usuario");
        jLabel10.setEnabled(false);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 264, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmcambumbito/img/volver.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 670, 272, 53));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmcambumbito/img/032 Sharpeye Eagle.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 670, 304, 53));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, -1, -1));

        jLabel11.setFont(new java.awt.Font("Corbel", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Ciudad");
        jLabel11.setEnabled(false);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, -1, -1));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 450, -1, -1));

        jLabel13.setFont(new java.awt.Font("Corbel", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Direccion");
        jLabel13.setEnabled(false);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Corbel", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Contraseña");
        jLabel14.setEnabled(false);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Corbel", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Confirmar Contraseña");
        jLabel15.setEnabled(false);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Corbel", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Pais");
        jLabel16.setEnabled(false);
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, -1));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, -1, -1));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, -1, -1));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, -1, -1));
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, -1, -1));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Corbel", 3, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Genero");
        jLabel23.setEnabled(false);
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, -1, -1));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, 100, 10));

        code.setBackground(new java.awt.Color(255, 255, 255));
        code.setFont(new java.awt.Font("Corbel", 3, 14)); // NOI18N
        code.setForeground(new java.awt.Color(0, 0, 0));
        code.setBorder(null);
        jPanel1.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 460, 120, 20));

        nombre.setBackground(new java.awt.Color(255, 255, 255));
        nombre.setFont(new java.awt.Font("Corbel", 3, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 0));
        nombre.setBorder(null);
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 280, 20));

        apellido.setBackground(new java.awt.Color(255, 255, 255));
        apellido.setFont(new java.awt.Font("Corbel", 3, 14)); // NOI18N
        apellido.setForeground(new java.awt.Color(0, 0, 0));
        apellido.setBorder(null);
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 280, 20));

        user1.setBackground(new java.awt.Color(255, 255, 255));
        user1.setFont(new java.awt.Font("Corbel", 3, 14)); // NOI18N
        user1.setForeground(new java.awt.Color(0, 0, 0));
        user1.setBorder(null);
        jPanel1.add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 280, 20));

        mail1.setBackground(new java.awt.Color(255, 255, 255));
        mail1.setFont(new java.awt.Font("Corbel", 3, 14)); // NOI18N
        mail1.setForeground(new java.awt.Color(0, 0, 0));
        mail1.setBorder(null);
        jPanel1.add(mail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 280, 20));

        telefono.setBackground(new java.awt.Color(255, 255, 255));
        telefono.setFont(new java.awt.Font("Corbel", 3, 14)); // NOI18N
        telefono.setForeground(new java.awt.Color(0, 0, 0));
        telefono.setBorder(null);
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 280, 20));

        direccion.setBackground(new java.awt.Color(255, 255, 255));
        direccion.setFont(new java.awt.Font("Corbel", 3, 14)); // NOI18N
        direccion.setForeground(new java.awt.Color(0, 0, 0));
        direccion.setBorder(null);
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, 280, 20));

        ciudad.setBackground(new java.awt.Color(255, 255, 255));
        ciudad.setFont(new java.awt.Font("Corbel", 3, 14)); // NOI18N
        ciudad.setForeground(new java.awt.Color(0, 0, 0));
        ciudad.setBorder(null);
        jPanel1.add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, 110, 20));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Corbel", 2, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 255));
        jButton3.setText("Resetear todo");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 620, 170, -1));

        sexo.setBackground(new java.awt.Color(255, 255, 255));
        sexo.setFont(new java.awt.Font("Corbel", 3, 14)); // NOI18N
        sexo.setForeground(new java.awt.Color(0, 0, 0));
        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        jPanel1.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 590, 100, -1));

        jLabel24.setBackground(new java.awt.Color(153, 0, 153));
        jLabel24.setFont(new java.awt.Font("Corbel", 3, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 0, 204));
        jLabel24.setText("©2018-BMCAMBUMBUTO");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 790, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paisActionPerformed

    private void contrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        new admin().setVisible(true);
         this.setVisible(false); 
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        nombre.setText("");
        apellido.setText("");
        mail1.setText("");
        user1.setText("");
        contrasena.setText("");
        confirmar.setText("");
        telefono.setText("");
        direccion.setText("");
        ciudad.setText("");
        code.setText("");
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String url = "jdbc:mysql://localhost:3306/sga?useSSL=false"; 
        
        
       try{
             Connection conexion = (Connection) DriverManager.getConnection(url, "root", "Chino123");
                     Statement instruccion = conexion.createStatement();
                                 String sql = "select  user,mail,pass from usuarios";
                                 
        ResultSet result = instruccion.executeQuery(sql);
          //sql validacion r
        
        String Pass = contrasena.getText();
        String Nombre = nombre.getText();
        String Apellido = apellido.getText();
        String Ciudad = ciudad.getText();
        String Codigo = code.getText();
        String Telefono = telefono.getText();
        String Direccion = direccion.getText();
        String Pais = (String) pais.getSelectedItem();
        String Genero = (String) sexo.getSelectedItem();
        String admin = "no";
        
          //sql normal
           String user = user1.getText();
           String mail = mail1.getText();
           if(Codigo.equals("GM")){
                   admin ="si";
                 }
           String sqlv = "insert into usuarios(user,mail,pass,nombre,apellido,ciudad,codigo,telefono,direccion,pais,genero,admin)"+" values"
                   + "("+"'"+user+"'"+","+"'"+mail+"'"+","+"'"+Pass+"'"+","+"'"+Nombre+"'"+","+"'"+Apellido+"'"+","+"'"+Ciudad+"'"+","+"'"+Codigo+"'"+","+"'"+Telefono+"'"+","+"'"+Direccion+"'"+","+"'"+Pais+"'"+","+"'"+Genero+"'"+","+"'"+admin+"'"+")";
        while (result.next()) {
             
            if(mail.equals(result.getString(2))&&  !mail.equals("")){
           JOptionPane.showMessageDialog(null,"Este mail ya existe");
           
       }else if(user.equals(result.getString(1))&&!user.equals("")){
           JOptionPane.showMessageDialog(null,"Este user ya existe");
       }
            else if(!mail.equals(result.getString(2)) && !mail.equals("") &&!user.equals("")&& !user.equals(result.getString(1)) && !Pass.equals("")  && !Nombre.equals("") && !Apellido.equals("")
                    && !Ciudad.equals("") && !Codigo.equals("") && !Telefono.equals("") && !Direccion.equals("") && !Pais.equals("") && !Genero.equals("")){
               
                 instruccion.executeUpdate(sqlv);
                 
                  JOptionPane.showMessageDialog(null,"Se a registrado exitosamente!");
                  result.close();
                  instruccion.close();
                 conexion.close();
                  new admin().setVisible(true);
                  this.setVisible(false); 
        }
       
        }
           JOptionPane.showMessageDialog(null,"Por favor llenar todos los espacios");
       }
       catch(Exception e){
          
       }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextField code;
    private javax.swing.JPasswordField confirmar;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField mail1;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> pais;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField user1;
    // End of variables declaration//GEN-END:variables
}
