package bmcambumbito;

import java.awt.Color;
import java.awt.Graphics;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.swing.ImageIcon;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JOptionPane;

/**
 *
 * @author Oliver Smit, Camil Agramonte y Luis Feliz <BmCambumbito at gmail.com>
 */
public class reportes extends javax.swing.JFrame {

    /**
     * Creates new form registro
     */
    public reportes() {
        initComponents();
        setLayout(null);
        this.setLocationRelativeTo(null);
        setTitle("Reportes");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("img/ice.png")).getImage());

    }
    boolean bandera = false;
    boolean banderaa = false;
    boolean banderaaa = false;
    boolean banderaaaa = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator11 = new javax.swing.JSeparator();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        diaa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmcambumbito/img/ice.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 230, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmcambumbito/img/bglogin.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 820));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 132, 818, 10));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Corbel", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("Reportes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 70, 176, -1));

        jRadioButton2.setText("jRadioButton2");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1453, 317, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmcambumbito/img/volver.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 272, 53));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bmcambumbito/img/guardar.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 272, 53));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, -1, -1));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 450, -1, -1));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, -1, -1));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, -1, -1));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, -1, -1));
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, -1, -1));

        jLabel24.setBackground(new java.awt.Color(153, 0, 153));
        jLabel24.setFont(new java.awt.Font("Corbel", 3, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 0, 204));
        jLabel24.setText("©2018-BMCAMBUMBUTO");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 610, -1, -1));

        jButton3.setText("Mas recogida");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, -1, -1));

        jButton4.setText("recogidas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));

        jButton5.setText("faltan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, -1));

        jButton6.setText("genero");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, -1, -1));

        diaa.setBackground(new java.awt.Color(255, 255, 255));
        diaa.setForeground(new java.awt.Color(0, 0, 0));
        diaa.setBorder(null);
        jPanel1.add(diaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 540, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        new admin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked
 
 
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        bandera = false;
       banderaa = false;
        banderaaa = false;
        banderaaaa = true;
        repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       bandera = false;
        banderaa = true;
        repaint();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        bandera = true;
        repaint();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       bandera = false;
       banderaa = false;
        banderaaa = true;
        repaint();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     PrintWriter pw = null;
try {
    pw = new PrintWriter(new File("d:\\\\DiaSemanaMayorRecogida-20180809.csv"));
    StringBuilder builder = new StringBuilder();
String ColumnNamesList = "*Dia*...........*Semana*......*Mes*........*Recogidos*.....*Faltan*.....*Hombres*...*Mujeres*..*MejorDia*";


builder.append(ColumnNamesList +"\n");
builder.append("*8%*...............");
builder.append("*57%*........");
builder.append("*33%*...........");
builder.append("*80%*..............");
builder.append("*20%*.........");
builder.append("*66%*...........");
builder.append("*33%*......");
builder.append("*Miercoles*");
pw.write(builder.toString());
pw.close();
 JOptionPane.showMessageDialog(null,"Se a guardado exitosamente!");
} catch (FileNotFoundException e) {
    e.printStackTrace();
}




    }//GEN-LAST:event_jButton2ActionPerformed
            String dia = "15";
            String semana = "100";
            String Mes = "59";
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportes().setVisible(true);
            }
        });
    }

    public int MayorValor(int valor_rojo, int valor_verde, int valor_azul) {
        if (valor_rojo > valor_verde && valor_rojo > valor_azul) {
            return valor_rojo;
        } else if (valor_verde > valor_azul) {
            return valor_verde;
        } else {
            return valor_azul;
        }
    }

    public void paint(Graphics g) {
        super.paint(g);
        if (bandera == true) {

            String string_rojo = dia;
            String string_verde = semana;
            String string_azul = Mes;

            int int_rojo = Integer.parseInt(string_rojo);
            int int_verde = Integer.parseInt(string_verde);
            int int_azul = Integer.parseInt(string_azul);

            int valor_Mayor = MayorValor(int_rojo, int_verde, int_azul);

            int largo_Rojo = int_rojo * 400 / valor_Mayor;
            int largo_Verde = int_verde * 400 / valor_Mayor;
            int largo_Azul = int_azul * 400 / valor_Mayor;
            
              int Total = int_rojo + int_verde + int_azul;
            
             int porcentaje_rojo = int_rojo * 100 / Total;
            int porcentaje_verde = int_verde * 100 / Total;
            int porcentaje_azul = int_azul * 100 / Total;

            g.setColor(new Color(118, 181, 233));
            g.fillRect(600, 300, largo_Rojo, 40);
            g.drawString("Este Dia "+ porcentaje_rojo+"%", 490, 325);
  

            g.setColor(new Color(233, 118, 181));
            g.fillRect(600, 350, largo_Verde, 40);
            g.drawString("Esta Semana " + porcentaje_verde+"%" , 490, 375);
           

            g.setColor(new Color(118, 233, 170));
            g.fillRect(600, 400, largo_Azul, 40);
            g.drawString("Este Mes "+ porcentaje_azul+"%", 490, 425);
  
        }
        else if(banderaa == true){
              String Recogidos = "10";
              String Faltan = "5";
            
            int int_rojo = Integer.parseInt(Recogidos);
            int int_verde = Integer.parseInt(Faltan);
            int int_azul = Integer.parseInt("0");
            
            int total_votos = int_rojo + int_verde + int_azul;
            
            int grados_rojo = int_rojo * 360 / total_votos;
            int grados_verde = int_verde * 360 / total_votos;
            int grados_azul = int_azul * 360 / total_votos;
            
            int Total = int_rojo + int_verde + int_azul;
            
             int porcentaje_rojo = int_rojo * 100 / Total;
            int porcentaje_verde = int_verde * 100 / Total;
            int porcentaje_azul = int_azul * 100 / Total;
            
            g.setColor(new Color(118, 181, 233));
            g.fillArc(500, 280, 200, 200, 0, grados_rojo);
            g.fillRect(900, 320, 20, 20);
            g.drawString(porcentaje_rojo+"% Hombres", 775, 335);
            
            
            g.setColor(new Color(233, 118, 181));
            g.fillArc(500, 280, 200, 200, grados_rojo, grados_verde);
            g.fillRect(900, 350, 20, 20);
            g.drawString(porcentaje_verde +"% Mujeres", 775, 365);
            
            

        }else if(banderaaa == true){
            String Hombres = "80";
            String Mujeres = "20";
            String string_azul = "0";
            
            int int_rojo = Integer.parseInt(Hombres);
            int int_verde = Integer.parseInt(Mujeres);
            int int_azul = Integer.parseInt(string_azul);
            
            int Total = int_rojo + int_verde + int_azul;
            
            int largo_rojo = int_rojo * 400 / Total;
            int largo_verde = int_verde * 400 / Total;
            int largo_azul = int_azul * 400 / Total;
            
            int porcentaje_rojo = int_rojo * 100 / Total;
            int porcentaje_verde = int_verde * 100 / Total;
            int porcentaje_azul = int_azul * 100 / Total;
            
            g.setColor(new Color(118, 181, 233));
            g.fillRect(550, 350, largo_rojo, 50);
            g.setColor(new Color(255, 255, 255));
            g.drawString(porcentaje_rojo + "%  Recogidos", 555, 370);
            
            g.setColor(new Color(233, 118, 181));
            g.fillRect(550 + largo_rojo, 350, largo_verde, 50);
            g.setColor(new Color(255, 255, 255));
            g.drawString(porcentaje_verde + "%  Faltan", 555 + largo_rojo, 370);
            
       
        }else  if (banderaaaa == true) {

           String MaxR = "4/8/18";
           
            g.setColor(new Color(118, 181, 233));
            g.drawString("El dia de la semana con mas recogidas de paquetes es: "+"Miercoles", 610, 325);
            
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField diaa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    // End of variables declaration//GEN-END:variables
}
